name: Cloud Security Suite CI

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  secure-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Debugging: List files to confirm directory structure
      - name: List Files
        run: ls -R

      - name: Terraform Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          # Pointing specifically to the S3 Hardening folder
          directory: projects/01-S3-Hardening
          framework: terraform

      - name: Build Secure Container
        run: |
          # Change directory to where the Dockerfile actually lives
          cd projects/03-DevSecOps-CI-CD
          docker build -t security-tool:latest .
